import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='absolute bg-off-gray w-[48em] h-[48em] -z-10 rounded-[24em] -top-[22em] left-[16em]'></div>{children}</body>
    </html>
  )
}
