name: Deploy to Vercel

on:
  push:
    branches:
      - main # Replace 'main' with your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Adjust the Node.js version as needed

      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy to Vercel
        uses: vercel/action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Make sure to add this token as a GitHub secret
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Add this as a GitHub secret
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Add this as a GitHub secret
          vercel-args: --prod
